### ISSUE TITLE
Template - Como usuário eu quero ter um menu de navegação comum em todo o site para que eu possa navegar entre as diferente funções do sistema

### ISSUE THREAD

**Issue by lmatsuii** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-2-e1-proj-web-t13-pmv-ads-2023-2-e1-proj-roadmap#50]
Critérios de aceite:

- [x] O usuário consegue r para a home clicando no logo do sistema
- [x] O usuário consegue ir para a página de login clican no botao de login
- [x] O usuário consegue ir para a página "Sobre" pela navbar
- [x] O usuário consneguir ir para a páginna "Contato" pela navbar
- [x] O usuário consegue ir para a página "Suporte" pela navbar
